TOKEN=dummy

# Backend kamu (nanti kita buat di GitHub Pages)
APP_BASE_URL="https://headhonco7.github.io/azka-launcher-backend/api/v1/"

OPEN_WEATHER_BASE_URL="https://api.openweathermap.org/data/2.5/"
OPEN_WEATHER_API_KEY="KOSONGKAN_DULU"
CITY="Malang"

PROXY_IP=
PROXY_PORT=
