TOKEN="dummy"
APP_BASE_URL="https://broad-mud-0c5b.headhonco7.workers.dev/api/v1/"
OPEN_WEATHER_BASE_URL="https://api.openweathermap.org/data/2.5/"
OPEN_WEATHER_API_KEY="dummy"
CITY="Malang"

PROXY_IP="0.0.0.0"
PROXY_PORT="0"
